package practice.interview.ledger;

public enum LedgerEventType {
    ACCOUNT_CREATE,
    DEPOSIT_REQUESTED,
    DEPOSIT_CONFIRMED,
    WITHDRAW_REQUESTED,
    WITHDRAW_CONFIRMED,
    TRANSFER_IN_REQUESTED,
    TRANSFER_IN_CONFIRMED,
    TRANSFER_OUT_REQUESTED,
    TRANSFER_OUT_CONFIRMED,
}
